### ISSUE TITLE
Format for filling fields in "Add new region"

### ISSUE THREAD

**Issue by colinner** [kiselev-dv/gtfsmatcher#1]
Hi, this looks cool and I want to try it with Vancouver, CA GTFS data, since it is missing a lot of GTFS data from the local transit authority. I was able to compile and host the program on my Ubuntu, I just don't know what to put in the 6 textboxes under "Add new region". Thanks!

**Comment by kiselev-dv** [comment]
Hi @colinner I was rethinking this stuff, and trying to move from Angularjs for UI to React or Vue, so it's messy.

The only thing that matters is name: put let's say `vancouver` then add region, then go to `Match with osm`. Matcher will try to load data from `data/vancouver/google_transit.zip`

Other fields:
* `GTFS Ref tag` which tag to save `stop_code` from gtfs to. (`ref` or `gtfs:ref` for instance)
* `Name template` how to format stop name

**Comment by colinner** [comment]
Thanks for the tip! I finally got around to trying this, and it works great. Was able to find stop ref errors so easily. It seems many stop refs in Vancouver have swapped digit errors due to people hand transcribing them, including myself haha. Thanks for helping me help OSM, and making better transit data for my app.
